version: "3.8"

services:
  taker:
    working_dir: /code
    build:
      dockerfile: ./docker_taker/Dockerfile

  controller:
    working_dir: /code
    build:
      dockerfile: ./docker_controller/Dockerfile
    ports:
      - "8080:8080"
      - "80:80"