# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
      runs-on: [ubuntu-latest]
      steps:
      - name: Print Message
        run: echo "Hello"
  
