# This is a basic workflow to help you get started with Actions

name: CI

env:
  APP_NAME  : "KOREB"
  PKG_NAME  : "korb-ver-${{ github.sha }}"
  
# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
      runs-on: [ubuntu-latest]
      steps:
      - name: Print Message
        run: |
          echo "Application Name: ${{ env.APP_NAME }}"
          echo "Application Version: ${{ env.PKG_NAME }}"
      
      # Чекаутим код
      - uses: actions/checkout@v2
        # Устанавливаем python нужной версии
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: python -m pip install --upgrade pip
             pip install -r requirements.txt
      - name: pytest -v
        run: pytest -v .
        
     
  
